name: deltabalance
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - flet                # UI desktop
    - fastapi             # API futura
    - uvicorn             # servidor FastAPI
    - pydantic            # validación de datos
    - pytest              # tests